import { Class, Method, Property } from "runtime/reflect/class";
import { Module } from "runtime/module";
import { Declaration } from "runtime/reflect/declaration";
export declare class MangularModule {
    static loadCss(url: any): void;
    static getClassFunction(clazz: Class, modifier?: (instance: any) => any): Function;
    static getMethodFunction(method: Method): Function;
    static getPropertyValue(field: Property): void;
    static run(main: string, angular: any): void;
    static get(def: Declaration): MangularModule;
    private name;
    private module;
    private configs;
    private services;
    private providers;
    private controllers;
    private components;
    private directives;
    private filters;
    private runs;
    private constants;
    private factories;
    private values;
    private dependencies;
    private initialized;
    constructor(module: Module);
    addConfig(def: Declaration): void;
    addFactory(def: Declaration): void;
    addRun(def: Declaration): void;
    addProvider(def: Declaration): void;
    addService(def: Declaration): void;
    addController(def: Declaration): void;
    addDirective(def: Declaration): void;
    addComponent(def: Declaration): void;
    addFilter(def: Declaration): void;
    addValue(def: Declaration): void;
    addConst(def: Declaration): void;
    create(angular: any): any;
    init(angular: any): void;
    private initConfig(module, service);
    private initRun(module, service);
    private initConst(module, service);
    private initValue(module, service);
    private initProvider(module, service);
    private initFactory(module, service);
    private initService(module, service);
    private initController(module, service);
    private initDirective(module, service);
    private initComponent(module, service);
    private initFilter(module, service);
    run(angular: any): void;
}
